site_name: UX process toolkit
theme:
  name: material
  logo: assets/ao-logo.png

markdown_extensions:
  - admonition

extra_css:
    - css/styles.css

nav:
  - 'Intro': 'index.md'
  - 'Design principles': 'design-principles.md'
  - 'Design stages': 
    - 'Define the problem': 'design-stages/define.md'
    - 'Explore ideas': 'design-stages/explore.md'
    - 'Scope solutions': 'design-stages/scope.md'
    - 'Create designs': 'design-stages/design.md'
    - 'Handover & build': 'design-stages/build.md'
    - 'Measure & learn': 'design-stages/measure.md'
  - 'Methods':
    - 'UX discovery': 
      - 'Introduction': 'methods/discovery/index.md'
      - 'Stakeholder interviews': 'methods/discovery/stakeholder-interviews.md'
      - 'Competitor benchmarking': 'methods/discovery/competitor-benchmarking.md'
  - 'Deliverables':
    - 'Introduction': 'deliverables/index.md'
    - 'User personas': 'deliverables/personas.md'
    - 'Empathy maps': 'deliverables/empathy-maps.md'
  - 'Processes':
    - 'Lean UX': 'processes/lean-ux.md'
